name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ['8.0', '8.1']

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - name: Check composer configuration
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Check php-cs-fixer
        run: composer php-cs-fixer-dry-run

      - name: PHPUnit tests
        run: vendor/bin/phpunit -c phpunit.xml --coverage-clover clover.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
